import Header from '@/components/header';
import './globals.css';

import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Kecskemét Guessr',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='hu'>
      <head></head>
      <body
        className={`${inter.className} flex flex-col justify-between`}
        style={{
          backgroundSize: 'cover',
          backgroundPosition: 'center',
          backgroundAttachment: 'fixed',
          backgroundBlendMode: 'overlay',
          backgroundColor: 'white',
        }}
      >
        <div className='flex-1'>
          <Header />
          <div className='space-y-4 py-8 container mx-auto'>{children}</div>
        </div>
      </body>
    </html>
  );
}
