import Header from '@/components/header';
import './globals.css';

import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Kecskemét Guessr',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='hu'>
      <head />
      <body
        className={`${inter.className}`}
        style={{
          backgroundSize: 'cover',
          backgroundPosition: 'center',
          backgroundAttachment: 'fixed',
          backgroundBlendMode: 'overlay',
          backgroundColor: 'white',
        }}
      >
        <div className='h-screen flex flex-col'>
          <div className='h-min'>
            <Header />
          </div>
          <div className='flex flex-1 bg-[url(/Cifra_Palota.jpg)] bg-cover bg-transparent'>
            <div className='flex flex-1 backdrop-blur-sm'>
              <div className='flex-1 space-y-4 py-8 container mx-auto'>{children}</div>
            </div>
          </div>
        </div>
      </body>
    </html>
  );
}
